# Generated by Django 5.2.13 on 2026-04-20 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("tracks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprogress",
            name="checklist_items",
            field=models.ManyToManyField(blank=True, to="tracks.checklistitem"),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="completed_tasks",
            field=models.ManyToManyField(blank=True, to="tracks.task"),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tracks.track"
            ),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userprogress",
            unique_together={("user", "track")},
        ),
    ]
