# Generated by Django 5.2.13 on 2026-04-20 16:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Checklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название чек-листа"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Порядок")),
            ],
            options={
                "verbose_name": "Чек-лист",
                "verbose_name_plural": "Чек-листы",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Direction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Код направления"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Название направления"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Направление",
                "verbose_name_plural": "Направления",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название задания"),
                ),
                ("description", models.TextField(verbose_name="Описание задания")),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("text", "Текстовый ответ"),
                            ("single", "Один правильный ответ"),
                            ("multiple", "Несколько правильных ответов"),
                            ("code", "Код"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="Тип задания",
                    ),
                ),
                (
                    "correct_answer",
                    models.TextField(blank=True, verbose_name="Правильный ответ"),
                ),
                (
                    "points",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Баллы",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Порядок")),
            ],
            options={
                "verbose_name": "Задание",
                "verbose_name_plural": "Задания",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500, verbose_name="Текст пункта")),
                ("order", models.IntegerField(default=0, verbose_name="Порядок")),
                (
                    "checklist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="tracks.checklist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пункт чек-листа",
                "verbose_name_plural": "Пункты чек-листа",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TaskOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(max_length=500, verbose_name="Текст варианта"),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        default=False, verbose_name="Правильный вариант"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="tracks.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант ответа",
                "verbose_name_plural": "Варианты ответа",
            },
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название трека"),
                ),
                (
                    "short_description",
                    models.TextField(verbose_name="Краткое описание"),
                ),
                ("full_description", models.TextField(verbose_name="Полное описание")),
                (
                    "career_paths",
                    models.TextField(verbose_name="Карьерные перспективы"),
                ),
                (
                    "skills",
                    models.TextField(verbose_name="Навыки, которые вы получите"),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Длительность обучения"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Порядок отображения"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tracks/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "direction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="tracks.direction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Трек",
                "verbose_name_plural": "Треки",
                "ordering": ["direction", "order", "name"],
            },
        ),
        migrations.AddField(
            model_name="task",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="tracks.track",
            ),
        ),
        migrations.CreateModel(
            name="Guide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("content", models.TextField(verbose_name="Содержание")),
                ("order", models.IntegerField(default=0, verbose_name="Порядок")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guides",
                        to="tracks.track",
                    ),
                ),
            ],
            options={
                "verbose_name": "Гайд",
                "verbose_name_plural": "Гайды",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="checklist",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checklists",
                to="tracks.track",
            ),
        ),
        migrations.CreateModel(
            name="UserTaskAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.TextField(verbose_name="Ответ пользователя")),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Правильно"),
                ),
                (
                    "points_earned",
                    models.IntegerField(default=0, verbose_name="Полученные баллы"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="tracks.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка выполнения",
                "verbose_name_plural": "Попытки выполнения",
                "ordering": ["-created_at"],
                "unique_together": {("user", "task")},
            },
        ),
    ]
